---
title: "Capston NFL Win Prediction"
author: "Maurice Rankin"
date: "11/23/2019"
output: rmd
---
Capston NFL Win Prediction
Maurice Rankin
11/23/2019
#Installed nflscrapR to support scrapping data from NFL.com library(devtools) devtools::install_github(repo <- “maksimhorowitz/nflscrapR”, force=TRUE) devtools::install_github(“dgrtwo/gganimate”, force=TRUE) install.packages(‘caTools’)
#Loaded proper libraries needed library(nflscrapR) library(tidyverse) library(caTools)
#Web Scrapping Data and Binding all seasons for years 2009 to 2019 play1 <- season_play_by_play(2019) saveRDS(play1, “play_data_2019.rds”)
play2 <- season_play_by_play(2018) saveRDS(play2, “play_data_2018.rds”)
play3 <- season_play_by_play(2017) saveRDS(play3, “play_data_2017.rds”)
play4 <- season_play_by_play(2016) saveRDS(play4, “play_data_2016.rds”)
play5 <- season_play_by_play(2015) saveRDS(play5, “play_data_2015.rds”)
play6 <- season_play_by_play(2014) saveRDS(play6, “play_data_2014.rds”)
play7 <- season_play_by_play(2013) saveRDS(play7, “play_data_2013.rds”)
play8 <- season_play_by_play(2012) saveRDS(play8, “play_data_2012.rds”)
play9 <- season_play_by_play(2011) saveRDS(play9, “play_data_2011.rds”)
play10 <- season_play_by_play(2010) saveRDS(play10, “play_data_2010.rds”)
play11 <- season_play_by_play(2009) saveRDS(play11, “play_data_2009.rds”)
#binding play by play data into a signle play object play <- bind_rows(play1,play2,play3,play4,play5,play6,play7,play8,play9,play10, play11) saveRDS(play, “play_data.rds”)
#Scapring gameIDs for All Seasons into individual dataframes games2019 <- scrape_game_ids(2019) games2018 <- scrape_game_ids(2018) games2017 <- scrape_game_ids(2017) games2016 <- scrape_game_ids(2016) games2015 <- scrape_game_ids(2015) games2014 <- scrape_game_ids(2014) games2013 <- scrape_game_ids(2013) games2012 <- scrape_game_ids(2012) games2011 <- scrape_game_ids(2011) games2010 <- scrape_game_ids(2010) games2009 <- scrape_game_ids(2009)
#Binding all rows for game years 2009 to 2019 into one games dataframe games <- bind_rows(games2019, games2018, games2017, games2016, games2015, games2014, games2013, games2012, games2011, games2010, games2009) saveRDS(games, “games_data.rds”)
#Joining games and play datframes on game_ID and GameID play_final <- full_join(games, play, by = c(“game_id” = “GameID”)) saveRDS(play_final, “play_final.rds”) #Resulting data frame has 481629 observations and 112 variables
#Created simple variables to track the response in my model, track downs, quarters and using poswins to determian the winner.
play_final <- play_final %>% mutate(winner <- ifelse(home_score > away_score, home_team, away_team)) play_final <- play_final %>% mutate(poswins <- ifelse(winner == posteam, “Yes”,“No”)) play_finalqtr<-as.factor(play_f inalqtr) play_finaldown<-as.factor(play_f inaldown) play_finalposwins<-as.factor(play_f inalposwins)
#Filtering plays that did not actually occure during regulation noplay_data_filter = play_final %>% filter(PlayType != “No Play” & qtr != 5 & down != “NA”) %>% select(game_id, Date, posteam, HomeTeam, AwayTeam, winner, qtr, down, ydstogo, TimeSecs, yrdline100, ScoreDiff, poswins)
#Spliting filtered dataset and creating my training and test set.
set.seed(123) split <- sample.split(noplay_data_filter$poswins, SplitRatio <- 0.8) train <- noplay_data_filter %>% filter(split == TRUE) test <- noplay_data_filter %>% filter(split == FALSE) #test and train save point
train = cbind(noplay_data_filter, noplay_data_filter) # example with multiple duplicate columns train = test[,!duplicated(names(test))]
#Creating a logic regression model using the glm funciton and generating a summary of my model model_lg = glm(poswins ~ qtr + down + ydstogo + TimeSecs + yrdline100 + ScoreDiff, train, family = “binomial”) summary(model_lg)
#Creating a prediction to estimate win probabilites for plays in the training set pred <- predict(model_lg, train, type <- “response”) train <- cbind(train,pred)
#Prevention probabilty calculations focues on the home team data stats train <- mutate(train, pred1h = ifelse(posteam == HomeTeam, pred, 1 - pred))
#Ploting the win probability of the home team tht is selected in the game_ID as the game is being played #To test for a future game just input the gameID for the game being played on the day of the game (prefer after 2nd quarter starts) ggplot(data=(filter(train, game_id == “2016090800”)), aes(x <- TimeSecs,y <- pred)) + geom_line(size = 1, colour = “green”) + scale_x_reverse() + ylim(c(0,1)) + theme_minimal() + xlab(“Time Remaining (seconds)”) + ylab(“Home Win Probability”)
